pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg"
    }

    parameters {
        string(
            name: 'inventory',
            defaultValue: 'dev',
            description: 'Inventory file to use'
        )
    }

    stages {

        stage('Initial cleanup') {
            steps {
                deleteDir()
            }
        }

        stage('Checkout SCM') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/LydiahLaw/ansible-config-mgt.git'
            }
        }

        stage('Prepare Ansible For Execution') {
            steps {
                sh '''
                    echo "Workspace path:"
                    echo ${WORKSPACE}

                    echo "Fixing roles_path in ansible.cfg"
                    sed -i "s|^roles_path.*|roles_path=${WORKSPACE}/roles|" ${WORKSPACE}/deploy/ansible.cfg

                    echo "Final ansible.cfg:"
                    cat ${WORKSPACE}/deploy/ansible.cfg
                '''
            }
        }

        stage('Run Ansible playbook') {
            steps {
                ansiblePlaybook(
                    become: true,
                    colorized: true,
                    credentialsId: 'private-key',
                    disableHostKeyChecking: true,
                    installation: 'ansible',
                    inventory: "inventory/${params.inventory}",
                    playbook: 'playbooks/site.yml'
                )
            }
        }

        stage('Clean Workspace after build') {
            steps {
                cleanWs(
                    cleanWhenAborted: true,
                    cleanWhenFailure: true,
                    cleanWhenNotBuilt: true,
                    cleanWhenUnstable: true,
                    deleteDirs: true
                )
            }
        }
    }
}
