pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg"
    }

    parameters {
        string(name: 'inventory', defaultValue: 'dev', description: 'Target environment inventory')
    }

    stages {
        stage("Initial cleanup") {
            steps {
                dir("${WORKSPACE}") {
                    deleteDir()
                }
            }
        }

        stage('Checkout SCM') {
            steps {
                git branch: 'main', url: 'https://github.com/LydiahLaw/ansible-config-mgt.git'
            }
        }

        stage('Prepare Ansible For Execution') {
            steps {
                sh 'echo ${WORKSPACE}'
                
            }
        }

        stage('Run Ansible playbook') {
            steps {
                ansiblePlaybook(
                    become: true,
                    colorized: true,
                    credentialsId: 'private-key',
                    disableHostKeyChecking: true,
                    installation: 'ansible',
                    inventory: 'inventory/${inventory}',
                    playbook: 'playbooks/deploy-todo.yml'
                )
            }
        }

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
    }
}