pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg"
    }

    parameters {
        string(
            name: 'inventory',
            defaultValue: 'dev',
            description: 'Inventory file for environment'
        )
        string(
            name: 'ansible_tags',
            defaultValue: '',
            description: 'Ansible tags to run specific tasks'
        )
    }

    stages {

        stage('Initial cleanup') {
            steps {
                dir("${WORKSPACE}") {
                    deleteDir()
                }
            }
        }

        stage('Checkout SCM') {
            steps {
                git branch: 'main', url: 'https://github.com/LydiahLaw/ansible-config-mgt.git'
            }
        }

        stage('Prepare Ansible For Execution') {
            steps {
                sh '''
                    echo "Preparing Ansible"
                    sed -i "s|roles_path=.*|roles_path=${WORKSPACE}/roles|" deploy/ansible.cfg
                '''
            }
        }

        stage('Run Ansible playbook') {
            steps {
                script {
                    def tags = ""

                    if (params.ansible_tags) {
                        tags = "--tags ${params.ansible_tags}"
                    }

                    ansiblePlaybook(
                        become: true,
                        colorized: true,
                        credentialsId: 'private-key',
                        disableHostKeyChecking: true,
                        installation: 'ansible',
                        inventory: "inventory/${params.inventory}",
                        playbook: 'playbooks/site.yml',
                        extras: tags
                    )
                }
            }
        }

        stage('Clean Workspace after build') {
            steps {
                cleanWs(
                    cleanWhenAborted: true,
                    cleanWhenFailure: true,
                    cleanWhenNotBuilt: true,
                    cleanWhenUnstable: true,
                    deleteDirs: true
                )
            }
        }
    }
}
